### ISSUE TITLE
pretrained pth

### ISSUE THREAD

**Issue by AndSonder** [1343744768/Multiattention-UNet#1]
Could publish your model's pth please ?

**Comment by 1343744768** [comment]
> Could publish your model's pth please ?

We have updated the model, and the new model has stronger performance. See readme for details, and in the link to download the model, we have also updated our datasets division document.

**Comment by 1343744768** [comment]
> Could publish your model's pth please ?

https://pan.baidu.com/s/16Kv_pJVjjLKt1c0njHuGHw
code：pyfz

**Comment by AndSonder** [comment]
Thank you very much !
